apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |-
    [server]
    protocol = http
    http_port = 3000
    domain = localhost
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    enable_gzip = true
    [users]
    allow_sign_up = true
    [auth.anonymous]
    enabled = true
    org_name = Anonymous
    org_role = Viewer
    [database]
    type = sqlite3
    path = /data/grafana.db
    host = localhost:3306
    name = grafana
    user = root
    password = grafana
    [session]
    provider = memory
    [analytics]
    check_for_updates = true
    [log]
    mode = console
    level = info
    format = json

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.1.6
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config-volume
          mountPath: /etc/grafana
        - name: data-volume
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: grafana-config
      - name: data-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP