
#apiVersion: v1
#kind: Namespace
#metadata:
  #name: app-bootcamp
  #labels:
    #name: app-bootcamp
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: app-bootcamp
    name: app-bootcamp
    namespace: app-bootcamp
spec:
    replicas: 2
    selector:
        matchLabels:
            app: app-bootcamp
    template:
        metadata:
            labels:
                app: app-bootcamp
        spec:
            containers:
            - name: app-bootcamp
              image: ghcr.io/diazalonsodavid/bootcamp/app-project:0.0.1.7
              imagePullPolicy: Always
              ports:
                - name: 
                  containerPort: 5005
              lifecycle:
                postStart:
                  exec:
                    command: ["/bin/bash", "-c", "python manage.py makemigrations app; python manage.py migrate"]
            imagePullSecrets:
            - name: app-bootcamp