apiVersion: v1
kind: Service
metadata:
  name: app-bootcamp
  namespace: app-bootcamp
spec:
  type: LoadBalancer
  selector:
    app: app-bootcamp
  ports:
    - name: http
      protocol: TCP
      port: 5005
      targetPort: 5005