kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJaR2xoZW1Gc2IyNXpiMlJoZG1sa09qWTVOV1prWmpBd1pEbGxPR0UxTnpBek1EUXpPV016WVRaaVpqa3hObUZoWmprek1USTNaamc9In19fQ==
