name: Repository Dispatch
#on:
  #repository_dispatch:
    #types: [trigger-cd]
on:
  push:
    branches:
      - 'main'

jobs:
  trigger-cd:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        do_token: ${{ secrets.DO_TOKEN }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_TOKEN }}
        clusterName: bootcamp-project
    
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save bootcamp-project
        

    
