name: Repository Dispatch
#on:
  #repository_dispatch:
    #types: [trigger-cd]
on:
  push:
    branches:
      - 'main'

jobs:
  trigger-cd:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        do_token: ${{ secrets.DO_TOKEN }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
       token: ${{ secrets.DO_TOKEN }}

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.3
    
    - name: Terraform init, plan and apply
      run: |
        echo `pwd` 
        cd terraform
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        echo "** Running Terraform Init**"
        terraform init

        echo "** Running Terraform Validate**"
        terraform validate

        echo "** Running Terraform Apply**"
        terraform apply -auto-approve -var="do_token=${{ secrets.DO_TOKEN }}"
    
    - name: Save kubeconfig
      run: doctl kubernetes cluster kubeconfig save bootcamp-project

    - name: Set up kubectl
      uses: matootie/dokube@v1.4.0
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: bootcamp-project
    # Run any kubectl commands you want!
    - name: Get nodes
      run: kubectl get nodes
#    - name: Terraform Destroy
#      run: |
#        echo "** Running Terraform Destroy**"
#        terraform plan -destroy
#        terraform destroy -auto-approve
#      working-directory: ${{ github.event.inputs.tfpath }}
