name: Repository Dispatch
#on:
  #repository_dispatch:
    #types: [trigger-cd]
on:
  push:
    branches:
      - 'main'

jobs:
  trigger-cd:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        do_token: ${{ secrets.DO_TOKEN }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.3
    
    - name: Terraform init, plan and apply
      run: |
        echo `pwd` 
        cd terraform
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        echo "** Running Terraform Init**"
        terraform init

        echo "** Running Terraform Validate**"
        terraform validate
        
        echo "** Running Terraform Destroy**"
        terraform destroy -auto-approve
        env 
        echo "** Running Terraform Apply**"
        #terraform apply -auto-approve -var="do_token=${{ secrets.DO_TOKEN }}"
    - name: Terraform Destroy
      run: |
        echo "** Running Terraform Destroy**"
        terraform plan -destroy
#        terraform destroy -auto-approve
      working-directory: ${{ github.event.inputs.tfpath }}
