name: Repository Dispatch
#on:
  #repository_dispatch:
    #types: [trigger-cd]
on:
  push:
    branches:
      - 'main'

jobs:
  trigger-cd:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
        #TESTARGS: -parallel 20
        #DIGITALOCEAN_TOKEN: ${{ secrets.do_token }}
        SPACES_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        SPACES_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.3
    
    - name: Terraform init, plan and apply
      run: |
        cd /home/runner/work/app-project-devops/terraform/
        ls
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        echo "** Running Terraform Init**"
        terraform init

        echo "** Running Terraform Validate**"
        terraform validate

        echo "** Running Terraform Plan**"
        terraform plan

#        echo "** Running Terraform Apply**"
#        terraform apply -auto-approve
    - name: Terraform Destroy
      run: |
        echo "** Running Terraform Destroy**"
        terraform plan -destroy
#        terraform destroy -auto-approve
      working-directory: ${{ github.event.inputs.tfpath }}
